GeneradorDeExamenes.Web/Controllers/HomeController.cs
using GeneradorDeExamenes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GeneradorDeExamenes.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

GeneradorDeExamenes.Web/Controllers/IaController.cs
using GeneradorDeExamanes.Logica.Services;
using GeneradorDeExamenes.Entidades;
using GeneradorDeExamenes.Models;

using Microsoft.AspNetCore.Mvc;

namespace GeneradorDeExamenes.Web.Controllers;

public class IaController : Controller
{
    private readonly IIaService _iaService;
    private readonly IExamenService _examenService;
    private readonly ICategoriaService _categoriaService;

    public IaController(IIaService iaService, IExamenService examenService, ICategoriaService categoriaService)
    {
        _iaService = iaService;
        _examenService = examenService;
        _categoriaService = categoriaService;
    }

    public IActionResult GeneradorPreguntas()
    {
        return View(new ExamenViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> GenerateQuestions(ExamenViewModel examenModel)
    {
        try
        {
            var preguntasGeneradas = await _iaService.GenerateQuestions(examenModel);

            if (preguntasGeneradas != null && preguntasGeneradas.Any())
            {
                examenModel.Preguntas = preguntasGeneradas.Select(p =>
                {
                    var preguntaModel = new PreguntaModel();
                    preguntaModel.ParsearPregunta(p);
                    return preguntaModel;
                }).ToList();

                return View("MostrarPreguntas", examenModel);
            }
            else
            {
                ViewBag.Error = "No se pudieron generar preguntas.";
                return View("GeneradorPreguntas", examenModel);
            }
        }
        catch (Exception ex)
        {
            ViewBag.Error = "Error al generar preguntas: " + ex.Message;
            return View("GeneradorPreguntas", examenModel);
        }
    }

    public IActionResult MostrarPreguntas(ExamenViewModel examenModel)
    {
        return View(examenModel);
    }

    [HttpPost]
    public async Task<IActionResult> CorregirRespuestas(ExamenViewModel examenModel)
    {
        try
        {
            var examenConFeedback = await _iaService.GetFeedback(examenModel);

            if (examenConFeedback != null && !string.IsNullOrEmpty(examenConFeedback.Feedback))
            {
                examenModel.Feedback = examenConFeedback.Feedback;

                await _examenService.AddExamenAsync(examenModel);

                return View("MostrarFeedback", examenModel);
            }
            else
            {
                ViewBag.Error = "No se pudo obtener el feedback.";
                return View("MostrarPreguntas", examenModel);
            }

        }
        catch (Exception ex)
        {
            ViewBag.Error = "Error al obtener el feedback: " + ex.Message;
            return View("MostrarPreguntas", examenModel);
        }
    }


    public IActionResult MostrarFeedback(ExamenViewModel examenModel)
    {
        return View(examenModel);
    }

    public async Task<IActionResult> MostrarHistorial(int? idCategoria)
    {
        ViewBag.Categorias = _categoriaService.Listar();
        ViewBag.IdCategoriaSeleccionada = idCategoria;
        if (idCategoria.HasValue)
        {
            var examenes = _examenService.ListarPorCategoria(idCategoria.Value);
            var viewModel = ExamenViewModel.MapearLista(examenes.ToList());
            return View(viewModel);
        }
        else
        {
            var examenes = await _examenService.GetAllExamenesAsync();

            if (examenes == null)
            {
                examenes = new List<Examan>();
            }

            var viewModel = ExamenViewModel.MapearLista(examenes.ToList());
            return View(viewModel);
        }

    }

    public async Task<IActionResult> MostrarExamen(int id)
    {
        var examen = await _examenService.GetExamenByIdAsync(id);

        if (examen == null)
        {
            ViewBag.Error = "No se encontró el examen.";
            return RedirectToAction("MostrarHistorial");
        }

        var viewModel = new ExamenViewModel(examen);
        return View(viewModel);
    }



}

GeneradorDeExamenes.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GeneradorDeExamenes.Web/Views/Ia/GeneradorPreguntas.cshtml
@model ExamenViewModel

@{
    ViewData["Title"] = "GeneradorPreguntas";
}


<section id="central">
    <h2>Simulador de exámenes gratuito impulsado por IA</h2>
    <p>
        El simulador genera preguntas a partir de un texto, donde podrás
        responder y recibir una corrección en el momento, todo impulsado por
        la potencia de la IA.
    </p>
    <form class="texto w-100" asp-action="GenerateQuestions" method="post">
        <div class="form-group w-100">
            <label for="resumen">Texto detallado</label>
            <textarea class="form-control" name="Resumen" id="resumen" rows="10"></textarea>
        </div>
        <button type="submit" class="boton1 btn btn-lg btn-success w-50 mt-4">Generar examen</button>
    </form>
    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger">
            <strong>Error:</strong> @ViewBag.Error
        </div>
    }
</section>

GeneradorDeExamenes.Web/Views/Ia/MostrarExamen.cshtml
@model ExamenViewModel

@{
    ViewData["Title"] = "Mostrar Examen";
}
<div class="px-0 container">
    <h2 class="text-success mt-4 mb-3">Detalles del examen</h2>

    @if (!string.IsNullOrEmpty(Model.Feedback))
    {   
        <div class="d-flex gap-3">
            <div class="alert alert-success d-flex align-items-center text-center">
                Categoria:
                <div class="ms-2 fw-bold">
                    @Model.CategoriaNombre
                </div>
            </div>
            <div class="alert alert-success d-flex align-items-center text-center">
                Calificacion:
                <div class="ms-2 fw-bold">
                    @Model.Calificacion
                    </div>
            </div>
            <div class="alert alert-success d-flex align-items-center text-center">
                Fecha:
                <div class="ms-2 fw-bold">
                    @Model.FechaCreacion
                    </div>
            </div>
        </div>
        <div class="alert alert-info overflow-auto">
            <pre>@Model.Feedback</pre>
        </div>
    }
    else
    {
        <p class="text-warning">No se pudo obtener el feedback.</p>
    }

    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger">
            <strong>Error:</strong>@ViewBag.Error
        </div>
    }
</div>

GeneradorDeExamenes.Web/Views/Ia/MostrarFeedback.cshtml
@model ExamenViewModel

@{
    ViewData["Title"] = "MostrarFeedback";
}
<div class="container">
    <h2 class="text-primary">Feedback de las Respuestas</h2>

@if (!string.IsNullOrEmpty(Model.Feedback))
{
        <div class="alert alert-info">
    <pre>@Model.Feedback</pre>
        </div>
}
else
{
        <p class="text-warning">No se pudo obtener el feedback.</p>
}

@if (ViewBag.Error != null)
{
        <div class="alert alert-danger">
            <strong>Error:</strong>@ViewBag.Error
        </div>
}
</div> 

@*

<section id="central">
    <h2>Resultado de examen #8 - Clasificacion 8/10</h2>
    <div class="card-group" id="preguntas">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Pregunta #1</h5>
                <p class="card-text">
                    Some quick example text to build on the card title and make up the bulk of the
                    card's content.
                </p>
                <h5 class="card-title">Respuesta <span class="signo_correcto">✔️</span></h5>
                <p class="card-text">
                    Some quick example text to build on the card title and make up the bulk of the
                    card's content.
                </p>
                <hr>
                <h6 class="card-subtitle mb-2 text-muted">Aqui va el feedback</h6>
            </div>
        </div>
    </div>
        
    <button type="submit" class="boton1 btn btn-lg btn-success w-50">Guardar examen</button>

</section>

*@

GeneradorDeExamenes.Web/Views/Ia/MostrarHistorial.cshtml
@using GeneradorDeExamenes.Models;
@model List<ExamenViewModel>

@{
    ViewData["Title"] = "MostrarHistorial";
}

<section id="central">
    <h2 class="pb-3">Historial de exámenes</h2>

    <form method="get" asp-action="MostrarHistorial" class="form-inline mb-5">
        <div class="form-group mx-sm-3 mb-2 w-100 d-flex gap-3 align-items-center justify-content-between">
            <h5 class="card-title" for="IdCategoria">
                Categoría:
            </h5>
            <select id="IdCategoria" name="IdCategoria" class="form-control">
                <option value="">Todas</option>
                @foreach (var categoria in ViewBag.Categorias)
                {
                    if (ViewBag.IdCategoriaSeleccionada == categoria.IdCategoria)
                    {
                        <option selected="selected" value="@categoria.IdCategoria">@categoria.Nombre</option>
                    }
                    else
                    {
                        <option value="@categoria.IdCategoria">@categoria.Nombre</option>
                    }
                }
            </select>
       
            <button type="submit" class="btn btn-success">Filtrar</button>
        </div>
    </form>

    <div class="row w-100">
        @foreach (var examen in Model)
        {
            <div class="col-4 mb-3">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title"> Examen #@examen.IdExamen - @String.Format("{0:dd/MM/yyyy}", examen.FechaCreacion)</h5>
                        <p class="mb-0" style="font-size: 18px;"><b>Calificación: </b> @examen.Calificacion</p>
                        <p class="mb-3" style="font-size: 18px;"><b>Categoría: </b> @examen.CategoriaNombre</p>
                        <a href="@Url.Action("MostrarExamen", new { id = examen.IdExamen })" class="btn btn-md btn-success w-100 fw-bold">Ver Detalle</a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

GeneradorDeExamenes.Web/Views/Ia/MostrarPreguntas.cshtml
@model ExamenViewModel

@{
    ViewData["Title"] = "MostrarPreguntas";
}


<section id="central">
    <h2>Simulador de exámenes gratuito impulsado por IA</h2>

    @if (Model != null && Model.Preguntas.Any())
    {
        <form method="post" asp-action="CorregirRespuestas" class="responder py-3">
                @for (int i = 0; i < Model.Preguntas.Count; i++)
                {
                    <input type="hidden" name="Preguntas[@i].PreguntaTexto" value="@Model.Preguntas[i].PreguntaTexto" />
                    <li class="list-group-item w-100 my-1">
                        <p>@Model.Preguntas[i].PreguntaTexto</p>
                        <div class="form-group">
                            <label for="respuesta_@i" class="col-md-2 control-label">Respuesta:</label>
                            <div class="col-md-10">
                                <textarea  id="respuesta_@i" name="Preguntas[@i].RespuestaUsuario" class="form-control text-left">@Model.Preguntas[i].RespuestaUsuario</textarea>
                            </div>
                        </div>
                    </li>
                }

            <input type="hidden" name="Resumen" value="@Model.Resumen" />
            <button type="submit" class="boton1 btn btn-lg btn-success w-50 mt-2">Confirmar respuestas</button>

        </form>
    }
    else
    {
        <p class="text-warning">No se pudieron generar preguntas.</p>
    }

    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger">
            <strong>Error:</strong> @ViewBag.Error
        </div>
    }

</section>

GeneradorDeExamenes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeneradorDeExamenes.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GeneradorDeExamenes.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="header">
        <span class="logo">Pregunte.ar IA</span>
        <nav class="menu_de_navegacion">
            <a asp-controller="" asp-action="" class="menu">Home</a>
            <a asp-controller="Ia" asp-action="MostrarHistorial" class="menu">Historial</a>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3 w-100">
            @RenderBody()
        </main>
    </div>

    <footer>
        <p>2024 - Pregunte.ar IA</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>